version: '3.8'
services:
  mysqldb:
    image: mysql:8.0.30
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_DB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DB_DATABASE
    ports:
      - $MYSQL_DB_LOCAL_PORT:$MYSQL_DB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
      - ./db/scripts/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
  app:
    depends_on:
      - mysqldb
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQL_DB_ROOT_USER
      - DB_PASSWORD=$MYSQL_DB_ROOT_PASSWORD
      - DB_DATABASE=$MYSQL_DB_DATABASE
      - DB_PORT=$MYSQL_DB_DOCKER_PORT
    stdin_open: true
    tty: true
volumes: 
  db: